### ISSUE TITLE
[Suggestion] NAI4 Curated Preview Support

### ISSUE THREAD

**Issue by moon90175** [Metachs/sdwebui-nai-api#32]
NAI4 has recently opened for testing. It would be great if there could be corresponding updates.

**Comment by david419kr** [comment]
I made a simple implementation(only T2I works) for NAI4 cureted preview support, and opend a [pull request](https://github.com/Metachs/sdwebui-nai-api/pull/33) for it.
Not sure it will be merged here, but you can try [my forked version](https://github.com/david419kr/sdwebui-nai-api/) if you want to use it right now.
Character prompt function can be used with "CHAR:" prefix in prompt text. Of course, it only works proplerly when nai-diffusion-4-curated-preview selected at Model selector.
(Character Positions will only work as "AI's Choice", since I didn't understand how manual positioning works at NAIv4 character prompt function)  

"CHAR:" prefix for character prompt funtion can be used as below example:
![image](https://github.com/user-attachments/assets/8fa1ca79-30ec-496a-a49b-58700f640a3f)
![image](https://github.com/user-attachments/assets/c92b4caa-dec3-4cf8-a04c-ca3318a9066f)

**Comment by Deens599** [comment]
Downloaded the latest commit and just as a heads-up:
1) No model besides NAIv4cp works (trying to use NAIv3 ends up in the "Request 1/1: 400 Error: Error decoding request: invalid character 'N' looking for beginning of value" error)
2) Deliberate EulerA Bug and Prefer Brownian don't work: not only are their defaults not being applied correctly (on Euler A they should be False and True respectively as per the metadata of on-site generations, but if generated with the extension, they are being set to True and False with this, and any other, sampler when set to Default) but even trying to manually override them results in no change of the parameters (meaning parity with the website is impossible)

**Comment by david419kr** [comment]
@Deens599 Hi, I didn't realized that NAIv3 and older models broke, [the latest commit](https://github.com/david419kr/sdwebui-nai-api/commit/15a053cd193567d0baf4b4e00124f452caeca8ca) wil fix it.

**Comment by Metachs** [comment]
All V4 preview features should be fully supported now, results match site in all comparisons I've run.
