### ISSUE TITLE
Prompt info incorrectly saved to PNG

### ISSUE THREAD

**Issue by Wavuwavu** [Metachs/sdwebui-nai-api#6]
Hi, 

Recently after some update (sorry not sure which) I noticed the info saved to the images does not follow the usual NAI formatting and also claims the model of the image is the one currently loaded into automatic1111, plus (and the big issue for me using dynamic prompts) on batch count of 2+ the png info of the first image is what is saved to every image after the first.

**Comment by Metachs** [comment]
Fixed the issue with batch images using saved with incorrect metadata. 

Including the A1111 local metadata was intentional, as I found saving the full state useful. The original NAI metadata is all still there, it just adds A1111's as well. I added a setting (Save only NAI metadata) to disable this, and only save NAI metadata for original NAI images.

**Comment by Wavuwavu** [comment]
Thank you!
